[tool.poetry]
name = "python_code"
version = "0.1.0"
description = ""
authors = ["rich leblanc <rich.leblanc1@proton.me>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
